services:
  - type: web
    name: marketplace-kh-server
    env: node
    plan: free
    repo: https://github.com/chhunly45/Kh.Product.git
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: "MONGODB_URI"
        sync: false
      - key: JWT_SECRET
        value: "JWT_SECRET"
        sync: false
      - key: CLIENT_URL
        value: "CLIENT_URL"
        sync: false
      - key: RESEND_API_KEY
        value: "RESEND_API_KEY"
        sync: false
      - key: EMAIL_FROM
        value: "EMAIL_FROM"
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: "CLOUDINARY_CLOUD_NAME"
        sync: false
      - key: CLOUDINARY_API_KEY
        value: "CLOUDINARY_API_KEY"
        sync: false
      - key: CLOUDINARY_API_SECRET
        value: "CLOUDINARY_API_SECRET"
        sync: false
      - key: NODE_ENV
        value: production
        sync: false
