module.exports = [
  { name: 'Phones & Tablets', slug: 'phones-tablets', labelKh: 'ទូរស័ព្ទ និង ថេប្លេត', order: 1 },
  { name: 'Computers & Laptops', slug: 'computers-laptops', labelKh: 'កុំព្យូទ័រ និង ល៉ាបតុប', order: 2 },
  { name: 'Electronics', slug: 'electronics', labelKh: 'អេឡិចត្រូនិច', order: 3 },
  { name: 'Vehicles', slug: 'vehicles', labelKh: 'ឡាន', order: 4 },
  { name: 'Motorcycles', slug: 'motorcycles', labelKh: 'ម៉ូតូ', order: 5 },
  { name: 'Car Parts', slug: 'car-parts', labelKh: 'គ្រឿងបន្លាស់ឡាន', order: 6 },
  { name: 'Motorcycle Parts', slug: 'motorcycle-parts', labelKh: 'គ្រឿងបន្លាស់ម៉ូតូ', order: 7 },
  { name: 'Real Estate', slug: 'real-estate', labelKh: 'អចលនទ្រព្យ', order: 8 },
  { name: 'Furniture', slug: 'furniture', labelKh: 'គ្រឿងសង្ហារិម', order: 9 },
  { name: 'Home Appliances', slug: 'home-appliances', labelKh: 'គ្រឿងប្រើប្រាស់ផ្ទះ', order: 10 },
  { name: 'Fashion', slug: 'fashion', labelKh: 'ម៉ូដ', order: 11 },
  { name: 'Shoes & Bags', slug: 'shoes-bags', labelKh: 'ស្បែកជើង និង កាបូប', order: 12 },
  { name: 'Watches & Jewelry', slug: 'watches-jewelry', labelKh: 'នាឡិកា និង គ្រឿងអលង្ការ', order: 13 },
  { name: 'Beauty & Health', slug: 'beauty-health', labelKh: 'សម្រស់ និង សុខភាព', order: 14 },
  { name: 'Baby & Kids', slug: 'baby-kids', labelKh: 'ទារក និង កុមារ', order: 15 },
  { name: 'Books & Stationery', slug: 'books-stationery', labelKh: 'សៀវភៅ និង គ្រឿងសិក្សា', order: 16 },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', labelKh: 'កីឡា និង សកម្មភាពក្រៅផ្ទះ', order: 17 },
  { name: 'Tools & Equipment', slug: 'tools-equipment', labelKh: 'ឧបករណ៍ និង សម្ភារៈ', order: 18 },
  { name: 'Agriculture', slug: 'agriculture', labelKh: 'កសិកម្ម', order: 19 },
  { name: 'Pets', slug: 'pets', labelKh: 'សត្វចិញ្ចឹម', order: 20 },
  { name: 'Food & Drinks', slug: 'food-drinks', labelKh: 'អាហារ និង ភេសជ្ជៈ', order: 21 },
  { name: 'Services', slug: 'services', labelKh: 'សេវាកម្ម', order: 22 },
  { name: 'Jobs', slug: 'jobs', labelKh: 'ការងារ', order: 23 },
  { name: 'Business & Industrial', slug: 'business-industrial', labelKh: 'អាជីវកម្ម និង ឧស្សាហកម្ម', order: 24 },
  { name: 'Games & Toys', slug: 'games-toys', labelKh: 'ហ្គេម និង គ្រឿងលេង', order: 25 },
  { name: 'Other', slug: 'other', labelKh: 'ផ្សេងៗ', order: 26 }
];
